name: Tests

on:
  pull_request:
    types: [opened,synchronize]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Download system package lists
        run: sudo apt-get update
      - name: Install system dependencies
        run: sudo apt-get install -y --no-install-recommends unifdef
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Install gems
        run: gem install hoe minitest isolate
      - name: Setup the project
        run: rake newb
      - name: Run tests
        run: rake
